### ISSUE TITLE
Help Pages

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/UI#26]
Hi

can we add to the ingam help pages localisation?
atm the pages er in it here...

**Comment by kirirur** [comment]
Yes, sure we can add them. 

Do you have the translation?

**Comment by Caberhagen** [comment]
I work on the translations.
Its difficulty for me to translate from italian.

Work atm at the agb and then go forward to the help pages.

**Comment by kirirur** [comment]
Oh, I see... I can try to translate italian into english, but I need time.

**Comment by Caberhagen** [comment]
No problem.
we have time :)

**Comment by Caberhagen** [comment]
I found the guide pages.
Them needs locales to.

**Comment by kirirur** [comment]
Oh yes, I thought you were talking about it in the post. Instead you were referring to the .htm.it files. Am I right?

**Comment by Caberhagen** [comment]
yes, in /game/help/ i can create all htm.de files from htm.en files. but take it easy to create the htm.en files.
In /game/help/guide/ we need htm.lang files or locale.php.

**Comment by kirirur** [comment]
I would prefer the locale.php way for the guide.

**Comment by Caberhagen** [comment]
Yeah ok. If you add the needet code to the files, i can add the
translations. But no stres...
Am 01.09.2015 09:04 schrieb "Andrea Carolfi" <notifications@github.com>:

**Comment by Caberhagen** [comment]
Hi, the ingame help files are created.
Next i can work at the in game guide

CU

**Comment by kirirur** [comment]
Hello!

We can consider closed this issue?

**Comment by Caberhagen** [comment]
i think it's all done.
so we can close it now.
thx cu
