### ISSUE TITLE
I need a hint at donation page.

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/UI#33]
Hi

i addet the translations to the spende.php.
I don't see in the file spende.php what i have to chage to call my paypal.

Thnx

**Comment by kirirur** [comment]
Hello,

you need to customize the following lines:
```html
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="170063">
        <input type="image" src="gfx/paypal.gif" border="0" name="submit" alt="">
        <img alt="" border="0" src="https://www.paypal.com/it_IT/i/scr/pixel.gif" width="1" height="1">
      </form>
```
the exact code to add depends on your PayPal account and configured button. I think you need to modify the value of variable hosted_button_id.

**Comment by Caberhagen** [comment]
Thnx
