### ISSUE TITLE
Define admin mail at config.inc.php

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/UI#34]
I see at translation we use the mail adress direkt hardcodet.
we have to change thes addresses by any install.
So it's hard to remember at witch places all we have to chenge the address.

Better wen we can use it in config.inc.php from ui folder.
So it auto changed to the right address.

**Comment by kirirur** [comment]
Hello,

yes you're right. The admin email address is used sometimes in the code, if it will be configured in the config file it will be easier to modify it.

I see that the files using that address are:
* UI/game/modules/settings.php
* UI/game/modules/tools/world/reset_galaxy.php
* UI/pages/lost_password.php
* UI/supportcenter/pages/bulkmail.php
* Scheduler/main.php

**Comment by Caberhagen** [comment]
Thanks Saboti.
