### ISSUE TITLE
logbook.sprache.php

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/UI#42]
we have in the file text part 165 to 218 just in iatalien.
can anyone make the translations to english?

then i mak the translation to german.

**Comment by kirirur** [comment]
Hi,

I'll try to make an English translation of those strings.

**Comment by Caberhagen** [comment]
Thnx and take it easy.

CU

**Comment by kirirur** [comment]
Gosh... more then a year passed.... I'm sorry nothing as been provided yet...
