### ISSUE TITLE
Problem to build structure.

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/UI#49]
Hi @ all

after a long run in the game, i think i run in to a problem on build structure on some planets.
enough ress on the planet but not able to build structure, but research are working.
anyone see the same?

![t-planet](https://cloud.githubusercontent.com/assets/5205107/11149028/a7bc745e-8a20-11e5-94ed-2d9b73ff25e5.jpg)

![x-planet](https://cloud.githubusercontent.com/assets/5205107/11149064/df95e838-8a20-11e5-9ab7-2046c754c5d0.jpg)

**Comment by kirirur** [comment]
Hello,

do you have the AU (Astronomic Unit) limit set up? Does that planet exceed the optimal AU distance from the home world (I don't remember if it's 20 or 40 AU)?

**Comment by Caberhagen** [comment]
Hi

oh i don't know we have these setting. Ok it's from the AU. It's at 40000.
I have now raised up the value, But don't see a change.
The value are sored by planet generation?

**Comment by kirirur** [comment]
Yes, changing the constant does not affect the planet, there is a field in planets table, called structure_points that need to be raised up to 677.

**Comment by Caberhagen** [comment]
Thanks now all clear...
