### ISSUE TITLE
Up to date Version

### ISSUE THREAD

**Issue by Saboti** [stfc2/UI#52]
Hello,
hope everyone is fine :)

I just want to ask if it's possible to update the source to the last one live on http://www.stfc.it
There are some nice new features.

Greeting Saboti

**Comment by Saboti** [comment]
@kirirur @Kail72, quick direct Ping :)

**Comment by Kail72** [comment]
Hi there!!! Long time since last time, isnt't it? :)

Yeah, i can upload the live source code but i need some free time to do so, maybe this weekend :)

**Comment by Saboti** [comment]
> Hi there!!! Long time since last time, isnt't it? :)
> 
> Yeah, i can upload the live source code but i need some free time to do so, maybe this weekend :)

Yes, really long time! Hope you are well :)
This would be highly appreciated! Thanks you. I’am still interested in this Project.

**Comment by Saboti** [comment]
> Hi there!!! Long time since last time, isnt't it? :)
> 
> Yeah, i can upload the live source code but i need some free time to do so, maybe this weekend :)

Hi @Kail72 , friendly Reminder :) Would be very cool to get the least Version from you!
Thank you!

**Comment by Kail72** [comment]
Most of the sources should be updated now, i hope they are in working conditions...
